### ISSUE TITLE
sbs standardization interface data publishing

### ISSUE THREAD

**Issue by rogerlew** [rogerlew/wepppy#320]
https://www.nature.com/sdata/

## todo

- [ ] add fire outlines to map
- [ ] add dnbr maps/fires to interface (ability to filter for sbs or dnbr)
- [ ] generate graphs with vegetation percent cover (dnbr and sbs)
- [ ] are _reveg stack maps COGs (cloud optimized geotiffs)?

## workflow

1. explore and find fires (by ecoregion)
2. advanced filtering on sbs catalog for % high, moderate, low, or % forest, etc.
3. add fires to a collection of fires
4. specify area of interest for simulated SBS (as bbox, or watershed, could use utility watersheds)
5. generate simulated SBS map (e.g. api query to ME tool, or sbs model (ME or other) on weppcloud)
6. create revegetation simulated regrowth curves for weppcloud
7. create weppcloud reveg simulated run with simulated SBS map and simulated regrowth curves

## title ideation
Here are some potential paper title ideas for your workflow:

"Simulating Soil Burn Severity and Revegetation Dynamics: An Integrated Workflow Using WEPPCloud"
"Advanced Fire Modeling and Simulated Regrowth: A New Approach to Soil Burn Severity Analysis"
"Ecoregion-Based Fire Selection and Simulated SBS Mapping for Revegetation Forecasting"
"Combining Simulated Soil Burn Severity and Vegetation Regrowth for Post-Fire Ecosystem Recovery"
"From Fire to Regrowth: Modeling Soil Burn Severity and Revegetation in WEPPCloud"
"A Multi-Scale Approach to Simulating Soil Burn Severity and Vegetation Recovery"
"Predictive Modeling of Soil Burn Severity and Revegetation: A Workflow for WEPPCloud Simulations"
"Integrating Fire Severity Simulation and Post-Fire Vegetation Recovery in Dynamic Models"
"Advanced SBS Simulation and Regrowth Curves for Post-Fire Management: A WEPPCloud Approach"
"Exploring Ecoregion-Specific Fires: Simulating Burn Severity and Vegetation Regrowth for Impact Analysis"

**Comment by marianadobre** [comment]
10/23/2024
RL, MEM, MD

On WEPP-PUFF:
1.	Upload a shapefile or delineate an AOI
2.	Manually select fires adjacent to the shapefile/AOI and add them to a collection of fires
3.	Pull average pixel values by SBS class for the SBS maps and average and SD pixel values for the area under the AOI/shapefile the from the database by:
    -	Percent forest, shrubs, grasses, etc. from RAP
    -	Percent forest canopy cover prior to the fire from RAP
    -	Elevation
    -	Aspect
    -	Annual average precipitation from PRISM (800 m)
    -	Annual average temperature from PRISM (800 m)
    -	Other
4.	Once a list of fires is identified, submit the AOI and the list of fires to MEM BurnSev and 
    a.	Use BurnSev model and database to predict a SBS map for the AOI.
    b.	Use BurnSev model and University of Idaho database to predict a SBS map for the AOI.
5. Return SBS map where?

**Comment by rogerlew** [comment]
From Mike Billmire:
re: a way to check model status without having to check email

So I refreshed myself on the code and it looks like there are already a few options here:

1. One way to do this would be to just check the contents of the model results directory for the run_id provided when you submit a run- the app currently just hosts all model results publicly at:

[https://apps3.mtri.org/burnsev/static/model_results/[run_id]/](https://urldefense.com/v3/__https://apps3.mtri.org/burnsev/static/model_results/*5Brun_id*5D/__;JSU!!JYXjzlvb!nXdKd7vYaTiE1EQ078qVDk0x2r6SmVy003vI-k-6Nv-TvkFZkBgMdCj-rkoBuqA2OaRnva7wtxwLHF0kS3on$)

So just doing periodic checks for the presence of a [run_id]-_PredictedBurnSeverity.tif file in that directory 

2. Leave the thread parameter in the burnsev_api endpoint blank, and it will directly return the .tif as an HTTP response when complete.
